// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBauteil(arg1) {
  return window['go']['backend']['App']['CreateBauteil'](arg1);
}

export function CreateKunde(arg1) {
  return window['go']['backend']['App']['CreateKunde'](arg1);
}

export function CreateProjekt(arg1) {
  return window['go']['backend']['App']['CreateProjekt'](arg1);
}

export function ListBauteile() {
  return window['go']['backend']['App']['ListBauteile']();
}

export function ListKunden() {
  return window['go']['backend']['App']['ListKunden']();
}

export function ListProjekte() {
  return window['go']['backend']['App']['ListProjekte']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
