// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function CreateBauteil(arg1:backend.CreateBauteilRequest):Promise<domain.Bauteil>;

export function CreateKunde(arg1:backend.CreateKundeRequest):Promise<domain.Kunde>;

export function CreateProjekt(arg1:backend.CreateProjektRequest):Promise<domain.Projekt>;

export function ListBauteile():Promise<Array<domain.Bauteil>>;

export function ListKunden():Promise<Array<domain.Kunde>>;

export function ListProjekte():Promise<Array<domain.Projekt>>;

export function Startup(arg1:context.Context):Promise<void>;
