// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function CreateBauteil(arg1:backend.CreateBauteilRequest):Promise<domain.Bauteil>;

export function CreateKunde(arg1:backend.CreateKundeRequest):Promise<domain.Kunde>;

export function CreateProjekt(arg1:backend.CreateProjektRequest):Promise<domain.Projekt>;

export function ListBauteile():Promise<Array<domain.Bauteil>>;

export function ListFarben():Promise<Array<domain.Farbe>>;

export function ListFunktionen():Promise<Array<domain.Funktion>>;

export function ListHerstellungsarten():Promise<Array<domain.Herstellungsart>>;

export function ListKunden():Promise<Array<domain.Kunde>>;

export function ListMaterialien():Promise<Array<domain.Material>>;

export function ListOberflaechenbehandlungen():Promise<Array<domain.Oberflaechenbehandlung>>;

export function ListProjekte():Promise<Array<domain.Projekt>>;

export function ListReserven():Promise<Array<domain.Reserve>>;

export function ListTypen():Promise<Array<domain.Typ>>;

export function ListVerschleissteile():Promise<Array<domain.Verschleissteil>>;

export function Startup(arg1:context.Context):Promise<void>;
