// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBauteil(arg1) {
  return window['go']['backend']['App']['CreateBauteil'](arg1);
}

export function CreateKunde(arg1) {
  return window['go']['backend']['App']['CreateKunde'](arg1);
}

export function CreateLieferant(arg1) {
  return window['go']['backend']['App']['CreateLieferant'](arg1);
}

export function CreateProjekt(arg1) {
  return window['go']['backend']['App']['CreateProjekt'](arg1);
}

export function FilterBauteile(arg1) {
  return window['go']['backend']['App']['FilterBauteile'](arg1);
}

export function FilterKunden(arg1) {
  return window['go']['backend']['App']['FilterKunden'](arg1);
}

export function FilterLieferanten(arg1) {
  return window['go']['backend']['App']['FilterLieferanten'](arg1);
}

export function FilterProjekte(arg1) {
  return window['go']['backend']['App']['FilterProjekte'](arg1);
}

export function GetFilterConfig() {
  return window['go']['backend']['App']['GetFilterConfig']();
}

export function ListFarben() {
  return window['go']['backend']['App']['ListFarben']();
}

export function ListFunktionen() {
  return window['go']['backend']['App']['ListFunktionen']();
}

export function ListHerstellungsarten() {
  return window['go']['backend']['App']['ListHerstellungsarten']();
}

export function ListKunden() {
  return window['go']['backend']['App']['ListKunden']();
}

export function ListLieferanten() {
  return window['go']['backend']['App']['ListLieferanten']();
}

export function ListMaterialien() {
  return window['go']['backend']['App']['ListMaterialien']();
}

export function ListOberflaechenbehandlungen() {
  return window['go']['backend']['App']['ListOberflaechenbehandlungen']();
}

export function ListProjekte() {
  return window['go']['backend']['App']['ListProjekte']();
}

export function ListReserven() {
  return window['go']['backend']['App']['ListReserven']();
}

export function ListTypen() {
  return window['go']['backend']['App']['ListTypen']();
}

export function ListVerschleissteile() {
  return window['go']['backend']['App']['ListVerschleissteile']();
}

export function SaveFilterConfig(arg1) {
  return window['go']['backend']['App']['SaveFilterConfig'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Search'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function UpdateBauteil(arg1) {
  return window['go']['backend']['App']['UpdateBauteil'](arg1);
}

export function UpdateLieferant(arg1) {
  return window['go']['backend']['App']['UpdateLieferant'](arg1);
}
