// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBauteil(arg1) {
  return window['go']['backend']['App']['CreateBauteil'](arg1);
}

export function CreateKunde(arg1) {
  return window['go']['backend']['App']['CreateKunde'](arg1);
}

export function CreateProjekt(arg1) {
  return window['go']['backend']['App']['CreateProjekt'](arg1);
}

export function ListBauteile() {
  return window['go']['backend']['App']['ListBauteile']();
}

export function ListFarben() {
  return window['go']['backend']['App']['ListFarben']();
}

export function ListFunktionen() {
  return window['go']['backend']['App']['ListFunktionen']();
}

export function ListHerstellungsarten() {
  return window['go']['backend']['App']['ListHerstellungsarten']();
}

export function ListKunden() {
  return window['go']['backend']['App']['ListKunden']();
}

export function ListMaterialien() {
  return window['go']['backend']['App']['ListMaterialien']();
}

export function ListOberflaechenbehandlungen() {
  return window['go']['backend']['App']['ListOberflaechenbehandlungen']();
}

export function ListProjekte() {
  return window['go']['backend']['App']['ListProjekte']();
}

export function ListReserven() {
  return window['go']['backend']['App']['ListReserven']();
}

export function ListTypen() {
  return window['go']['backend']['App']['ListTypen']();
}

export function ListVerschleissteile() {
  return window['go']['backend']['App']['ListVerschleissteile']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
